- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please Enter your username
    private: false # user can see what they are entering
  - name: PASSWORD
    prompt: Please Enter your password
    private: True # user can't see what they are entering
  tasks:
  - name: print and check the values
    ansible.builtin.debug:
      msg: "username is: {{USERNAME}}, Password is: {{PASSWORD}}"